# SQLITE CONFIGURATION
# services:

#   redis:
#     image: redis:latest
#     ports:
#       - 6379:6379
#     command: ["redis-server", "--appendonly", "yes"]
#     volumes:
#       - redis-data:/data

#   redis-commander:
#     image: rediscommander/redis-commander:latest
#     environment:
#       - REDIS_HOSTS=local:redis:6379
#       - HTTP_USER=root
#       - HTTP_PASSWORD=secret
#     ports:
#       - 8081:8081
#     depends_on:
#       - redis
    
# volumes:
#   redis-data:

# SQLSERVER CONFIGURATION
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "123456A@bc"
      ACCEPT_EULA: "Y"
    platform: linux/amd64
    ports:
      - "1433:1433"